export default {
    "word" : [   
        "Pumpkin",
        "Rainbow",
        "Snowflake",
        "Stairs",
        "Starfish",
        "Strawberry",
        "Sun",
        "Tire",
        "Toothbrush",
        "Toothpaste",
        "Truck",
        "Football",
        "Moon",
        "Tree",
        "Grass",
        "Egg",
        "Cat",
        "Eiffel Tower",
        "Book",
        "Beard",
        "Bucket",
        "Bumble bee",
        "Camera",
        "Dog",
        "Camel",
        "Bird",
        "Coffee",
        "Guitar",
        "Car",
        "Lamp",
        "Apple",
        "Lollipop",
        "Magnet",
        "Flag"
    ]
}